#!/bin/bash

echo "TinyAF-Fetch"
echo
echo "OS $(cat /etc/os-release | grep NAME)"
echo "KERNEL $(uname -r)"
if command -v echo $SHELL >/dev/null; then
    echo "SHELL: Bash"
fi

if command -v pacman >/dev/null; then
    PACMAN="pacman"
fi

if command -v apt >/dev/null; then
    APT="apt/dpkg"
fi

if command -v apk >/dev/null; then
    APK="apk"
fi

if command -v emerge >/dev/null; then
    EMERGE="emerge/portage"
fi

if command -v xbps-install >/dev/null; then
    XBPS="xbps"
fi

if command -v nix >/dev/null; then
    NIX="nix"
fi

if command -v dnf >/dev/null; then
    DNF="dnf/rpm"
fi

if command -v zypper >/dev/null; then
    ZYPPER="zypper"
fi

if command -v yum >/dev/null; then
    YUM="yum"
fi

echo "PACKAGE MANAGERS $PACMAN $APT $APK $EMERGE $XBPS $NIX $DNF $ZYPPER $YUM $SLACK"
echo "DE $(echo $XDG_CURRENT_DESKTOP)"
echo "CPU $(awk -F': ' '/model name/ {print $2; exit}' /proc/cpuinfo)"
echo "GPU $(lspci | grep -E "VGA|3D" | sed 's/.*: //')"
echo
